### ISSUE TITLE
Allow external configuration

### ISSUE THREAD

**Issue by dragos** [scala/scala-abide#29]
We should have a configuration file to turn on/off each rule. We should give a serious thought on using the [scalastyle configuration](http://www.scalastyle.org/configuration.html) format.

At the minimum, it should allow:
- enabling/disabling rules based on class name
- set the desired warning/error level per rule
- optional parameters
- optional custom error message

An advantage of using scalastyle format is that we could reuse some of the UI for configuration (Eclipse, IntelliJ), and keep all style-related settings in one file which is convenient for users.

**Comment by SethTisue** [comment]
Abide is superseded by https://github.com/scalacenter/scalafix; closing all issues
