### ISSUE TITLE
sealed type should declare supertypes shared by its subclasses

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-abide#41]
The below is a code smell because the lub of `::` and `Nil` will have to include `Serializable` in addition to `List`, the natural lub:

```
sealed trait List[+T]
final class ::[+T] extends List[T] with Serializable
final object Nil extends List[Nothing] with Serializable
```

**Comment by SethTisue** [comment]
Abide is superseded by https://github.com/scalacenter/scalafix; closing all issues
