### ISSUE TITLE
self-type impossible to realize, class cannot be instantiated

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-abide#42]
Original: https://issues.scala-lang.org/browse/SI-6787

The following code compiles but A cannot be instantiated nor subclassed.

```
class B
class A { self:B => }
```

It might be nice to have a warning or error that A is useless.

**Comment by adriaanm** [comment]
Even more so for objects with a self type that's not a supertype of the object itself. Should we deprecate self types outside of traits?

**Comment by retronym** [comment]
While we're at it, we could also warn for refinement types that have irreconcilable.

```
class C; class D; type X = C with D
```

See `areIrreconcilableAsParents` in the typer checker for the logic to detect when to warn.

**Comment by SethTisue** [comment]
Abide is superseded by https://github.com/scalacenter/scalafix; closing all issues
