### ISSUE TITLE
Timeline for release version. 

### ISSUE THREAD

**Issue by hanfeisun** [scala/scala-abide#43]
I found scala-abide might be the better choice of scala linters than others. It would be great if it could be known when to be ready for general use..

Thanks!

**Comment by hanfeisun** [comment]
https://secure.phabricator.com/D10405

Here is a propose to add scala linter support to phabricator officially, scala-abide seems one of top choices.. However, it looks not clear when will it be available..

**Comment by dragos** [comment]
Hey, thanks for pointing out the Phabricator discussion.

We don't have an ETA yet, but I think we're not far from a 0.1 release. We'll have a better estimate after ScalaDays (in 2 weeks).

**Comment by extesy** [comment]
@dragos do you have some ETA now that ScalaDays are over?

**Comment by SethTisue** [comment]
see https://github.com/scala/scala-abide/issues/69#issuecomment-261976673
