### ISSUE TITLE
False positive for unused value when defining partial functions

### ISSUE THREAD

**Issue by leifwickland** [scala/scala-abide#44]
A false positive for an unused values is identified in the following code

``` scala
  def stripProtocol(str: String): String = {
    Seq("http://", "https://").
      collectFirst { case protocol if (str.startsWith(protocol)) => str.substring(protocol.length) }.
      getOrElse(str)
  }
```

The error message is:

```
warning: value defaultCase$ is not used.
      collectFirst { case protocol if (str.startsWith(protocol)) => str.substring(protocol.length) }.
                   ^
```

(Apologies if this doesn't produce a reproducible test case. I'm attempting to replicate an example from a closed code base. If you struggle to produce the reported error, I'd be happy to attempt to offer a better example.)

**Comment by SethTisue** [comment]
Abide is superseded by https://github.com/scalacenter/scalafix; closing all issues
