### ISSUE TITLE
False positive for unused value when ignoring monadic result in for comprehension

### ISSUE THREAD

**Issue by leifwickland** [scala/scala-abide#45]
A false positive for unused value is generated when when ignoring monadic result in for comprehension, such as in the example code from @eed3si9n's ["Learning Scalaz"](http://eed3si9n.com/learning-scalaz/Monad+transformers.html):

``` scala
val pop: StateTReaderTOption[Config, Stack, Int] = {
         import StateTReaderTOption.{get, put}
         for {
           s <- get[Config, Stack]
           val (x :: xs) = s
           _ <- put(xs)
         } yield x
       }
```

The error message is:

```
value _ is not used. 
           _ <- put(xs)
           ^      
```

(Apologies if this doesn't produce a reproducible test case. I'm attempting to replicate an example from a closed code base. If you struggle to produce the reported error, I'd be happy to attempt to produce a better example.)

**Comment by SethTisue** [comment]
Abide is superseded by https://github.com/scalacenter/scalafix; closing all issues
