### ISSUE TITLE
implicit val that resolves to itself

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-abide#56]
```
implicit val stringToInt: Function1[String, Int] = new Function1[String, Int] { def apply(s: String): Int = s.toInt }
```

**Comment by bhattacharyyasom** [comment]
Why is this not considered a bug ?
Adding a reference to a user question who reported the same issue.

[http://stackoverflow.com/questions/37022552/scala-implicit-completing-itself/37022955?noredirect=1#comment61601791_37022955](url)

**Comment by SethTisue** [comment]
Abide is superseded by https://github.com/scalacenter/scalafix; closing all issues
