### ISSUE TITLE
pattern matching analysis with inferred finality

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-abide#57]
Not sure what this means, migrated from https://issues.scala-lang.org/browse/SI-8311

**Comment by retronym** [comment]
Perhaps I meant: if the user assumes a closed world for some subset of types, the compiler could mark some classes as "effectively final". This yields additional warnings for "fruitless type tests".

**Comment by SethTisue** [comment]
Abide is superseded by https://github.com/scalacenter/scalafix; closing all issues
