### ISSUE TITLE
Unnecessary string interpolator

### ISSUE THREAD

**Issue by paddymahoney** [scala/scala-abide#63]
Would detect strings using the interpolator syntax that didn't $ splice any identifier values: 

```
object StringInterpolator {
  val flagged = s"no.identifier.spliced"
  val notFlagged = s"$flagged.is.spliced"
}
```

**Comment by som-snytt** [comment]
`s` ought to be a macro like `f` that emits a string literal. In general, you don't know that the interpolator is unnecessary. For instance, `f"%n"` is not a constant.

**Comment by SethTisue** [comment]
Abide is superseded by https://github.com/scalacenter/scalafix; closing all issues
