### ISSUE TITLE
Is this project ABANDONED??

### ISSUE THREAD

**Issue by wpc009** [scala/scala-abide#69]
It seems that there is no commits for over a year. And no response to issues.
Is this project still living?
Can we use it on our recent project?

**Comment by dragos** [comment]
Let's call it "dormant". Probably after Scala 2.12 is out there will be some more activity. We'd be happy to help contributors though. You can give it a try on your project already, but you'd need to built it yourself.

**Comment by som-snytt** [comment]
Probably it just needs a much better name. Something sexier than wart but which echoes its provenance. "libido"? A neologism would be "abido".

**Comment by jarrodwb** [comment]
By looking at the commit history it looks like the project has been revived. Indeed the 2.12 release looks like it was a turning point.

**Comment by SethTisue** [comment]
If everyone is just waiting around for Lightbend to do all the work on this, well, that might not happen. If there's anyone out there who wants to help respond to issues, review pull requests, be a maintainer, etc, please do. The lights are back on, now, certainly.

Competition is also welcome. Abide is partly a real project and partly just an idea and a demonstration of what Adriaan thinks the right approach for writing a semantically aware Scala linter is. (Namely, a plugin that runs after typer.)

**Comment by SethTisue** [comment]
The lights are back on, anyway.

If anyone is waiting for Lightbend to do all the work needed to make Abide into the premier Scala linter, that might not happen. Hopefully a community will form around this repo? Community participation is welcome with responding to issues, reviewing PRs, and so on.

**Comment by SethTisue** [comment]
new thread on this: https://contributors.scala-lang.org/t/whats-the-status-of-abide/609

**Comment by som-snytt** [comment]
So the new answer is, "It is now."

**Comment by frgomes-hmrc** [comment]
Reading the thread pointed out by Seth, it looks to me that Abide and ScalaFix aim two very different aims, despite their guts may look similar:

1. Abide aims warning/stopping/whatever compilation when undesirable code constructs are found;
2. Scalafix aims to transform acceptable 2.11 code into acceptable 2.12 and beyond.

From the perspective of someone willing to find undesirable code, ScalaFix looks like a tool which transform old undesirable code into brand new and shinny undesirable code.

From the list of "Rewrites" in the ScalaFix documentation... even from the list of planned "Rewrites"... I don't see a one which could be understood like...

> As a developer, I want to get a compilation error when I've written code which does not conform to architectural patterns defined by group XYZ.

I think this is important. Big projects may define stringent rules which enforces the code to comply to certain architectural patterns. At this point in time, someone is not really interested on converting old code into new code... this may happen later... true!... but that person is only interested on getting compilation errors when the code does not follow the architectural patterns.

Thougths?

**Comment by SethTisue** [comment]
> Scalafix aims to transform [...] code

I'm suggesting broadening Scalafix's aims.

**Comment by som-snytt** [comment]
I'd like a tool that transforms ichoran code into tpolecat code and back.

**Comment by SethTisue** [comment]
Scalafix has officially taken up the linting cause: http://scala-lang.org/blog/2017/09/11/scalafix-v0.5.html
