### ISSUE TITLE
Run abide in the community build

### ISSUE THREAD

**Issue by retronym** [scala/scala-abide#82]
Wouldn't it be swell if we could periodically run abide across the whole [community build](https://github.com/scala/community-builds)?

Benefits:
  - Find crasher bugs in Abide
  - Manually inspect a sample of the reported results (especially for newly added rules) to check for false positives
  - Provide some marketing collateral by finding bugs in the wild!

**Comment by SethTisue** [comment]
@cunei is there something in dbuild that could add `addSbtPlugin(... "abide" ...)` to every project?

**Comment by cunei** [comment]
@SethTisue The astonishingly complete dbuild documentation suggests that it is possible to run arbitrary bash commands, by wrapping them into an eval and injecting them in the "extra.commands" field. They will be executed after dependency rewriting, and before building. For instance:
```
extra.commands: [ "eval Process(Seq(\"ls\",\"-l\")).lines foreach println" ]
```
You could use this trick to inject an "abide.sbt" file into every project, I suppose :)

**Comment by cunei** [comment]
There is also the "post-commands" option: those commands are run after building and testing.

**Comment by SethTisue** [comment]
relocated to https://github.com/scala/community-builds/issues/616
