### ISSUE TITLE
Drop support for Scala 2.10

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-abide#87]
@adriaanm any objection?

(I'm even tempted to suggest we drop 2.11 too...)

**Comment by dwijnand** [comment]
Which support for 2.10? The only one that exists is for the sbt plugin, and there's no choice there.

**Comment by SethTisue** [comment]
oh, then all that needs to be done is update the readme, which says "Activate the sbt-abide plugin in both Scala 2.10 and 2.11 projects" and "This mode can run on Scala 2.10 projects...".  I'll make it so

**Comment by SethTisue** [comment]
there is also a little bit of code for 2.10 support in `sbt-plugin/src/main/scala/scala/tools/abide/AbideSbtPlugin.scala`, as alluded to in the readme.

note that the 2.10 support is via `-Xsource:2.10`, not via actually building the scala-abide library on 2.10. so "The only one that exists is for the sbt plugin" isn't actually true. Regardless, I think we should drop it.

**Comment by dwijnand** [comment]
Ah, I see.

**Comment by adriaanm** [comment]
+1
